apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: yara-image
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/yara-image/yara-image@sha256:6ba9a9e706489fb8dadacdc970fc042791eed236e906f0f7f4183f80953549ef
        name: container-image
        resources: {}
status: {}
