apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: yara-image
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/yara-image/yara-image@sha256:72366df116deef4c4eae847463cf2290d6fce496e466c7fdaa25df736162bad3
        name: container-image
        resources: {}
status: {}
