apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: yara-image
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/brianwcook-tenant/yara-image/yara-image@sha256:6ea6b4eb6a9936f8791a38de11b23277eac1716971d31193322f4c4ac86ccf7e
        name: container-image
        resources: {}
status: {}
