apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: yara-image
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: yara-image
    app.kubernetes.io/part-of: yara-image
  name: yara-imageunon
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: yara-image
    weight: 100
status: {}
